monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        nested:
            type: stream
            path: php://stderr
            level: error
            formatter: monolog.formatter.json
#        console:
#            type: console
#            process_psr_3_messages: false
#            level: debug
#            channels: ["!event"]
